### ISSUE TITLE
json.dumps() fails on unprintable character

### ISSUE THREAD

**Issue by nitrocode** [smartsheet-platform/Smartsheet-Data-Tracker#2]
Hi, just wanted to share a patch with you.

Noticed that json.dumps() fails on an unprintable character so I added a try / except to see if the payload fails and if it does, it checks each value and if a value fails to json.dumps() then it corrects the value.

https://github.com/nitrocode/Smartsheet-Data-Tracker/commit/bdc4fad488d81e8062914597f5513a937ff68637

I'm not sure how to merge it. I checked out the code, added the new lines, tested it, committed it, pushed it, and then from the github website I created a pull request.

**Comment by stmcallister** [comment]
Thanks for the pull request. But, as mentioned in the pull request comments, if we can't reproduce the error to test the bug fix, then we'll wait on merging the change.
