### ISSUE TITLE
Smartsheet API 1.1 Deprecation as of July 31, 2016

### ISSUE THREAD

**Issue by nitrocode** [smartsheet-platform/Smartsheet-Data-Tracker#4]
Received an email on this recently.

https://www.smartsheet.com/blog/july-2015-api-v2-launch

Do you think it would be an easy transition to move from API 1.1 to API 2.0? I haven't searched through the APIs to see what the major differences are but it seems that the apiURL could easily be changed in the settings/app.json file.

**Comment by nitrocode** [comment]
It was very easy. See this pull change.

https://github.com/smartsheet-platform/Smartsheet-Data-Tracker/pull/5

**Comment by stmcallister** [comment]
Thanks for the pull request! I removed the checks for the API version, since those shouldn't be needed.
