### ISSUE TITLE
How to map versions?

### ISSUE THREAD

**Issue by Shikaka** [smartsheet-platform/Smartsheet-Data-Tracker#6]
RESTAPI Jira return
```json
{
"fixVersions": [2]
0:  {
"name": "6.11.0"
}
1: {
"name": "6.11.0"
}
```

how can i map it?

**Comment by stmcallister** [comment]
Mapping arrays is a little tricky, as you can only map a single array element to a column. 

You'll reference the name of the field in lowercase, such as `fixversions`. 

Then, you would add the element of the array you want to map, `fixversions0`. 

And, finally, if that element is an object you would but the name of the value you want to map from that object. 

So, for getting the name of the first Fix Version applied to an issue you would create a map like this:
```
{
	"sourceKey":"fixversions0Name",
	"sheetColumn":"Fix Version"
}
```

**Comment by Shikaka** [comment]
thx. that's work and enough for my issue
